# Generated by Django 3.2.6 on 2021-08-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
