# Generated by Django 3.2.6 on 2021-08-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrow', '0002_alter_barrow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
